zuul:
  routes:
    users:
      path: /test/**
      #write here the route of the called Rest API, GET /greeting is the URL.
      url: http://example.com/greeting


logging:
  level:
    org:
      springframework:
        cloud:
          netflix: trace
